// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBP29AttcoDULg6YHON3q2YfuA6o10DHk',
    appId: '1:441390678942:web:e311db134ea91131438c8f',
    messagingSenderId: '441390678942',
    projectId: 'nutriscan-fbdf8',
    authDomain: 'nutriscan-fbdf8.firebaseapp.com',
    storageBucket: 'nutriscan-fbdf8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9_bgJ5mrMrMKSyutbmTtVUg09utFj1JI',
    appId: '1:441390678942:android:6a2dd5cf90e47b37438c8f',
    messagingSenderId: '441390678942',
    projectId: 'nutriscan-fbdf8',
    storageBucket: 'nutriscan-fbdf8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5dan0dXQ6vZInv-XlEiPBfY0gk-Mzw3o',
    appId: '1:441390678942:ios:80d845a2b97db374438c8f',
    messagingSenderId: '441390678942',
    projectId: 'nutriscan-fbdf8',
    storageBucket: 'nutriscan-fbdf8.appspot.com',
    iosClientId: '441390678942-kbv2sa93d68u21klje1ioo5ht9kk3d9i.apps.googleusercontent.com',
    iosBundleId: 'com.monik.nutriscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5dan0dXQ6vZInv-XlEiPBfY0gk-Mzw3o',
    appId: '1:441390678942:ios:80d845a2b97db374438c8f',
    messagingSenderId: '441390678942',
    projectId: 'nutriscan-fbdf8',
    storageBucket: 'nutriscan-fbdf8.appspot.com',
    iosClientId: '441390678942-kbv2sa93d68u21klje1ioo5ht9kk3d9i.apps.googleusercontent.com',
    iosBundleId: 'com.monik.nutriscan',
  );
}
